"""add column to project

Revision ID: ca4317cbbc9b
Revises: 0b09c12a007a
Create Date: 2019-08-05 20:15:07.744040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4317cbbc9b'
down_revision = '0b09c12a007a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('web', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'web')
    # ### end Alembic commands ###
